[tool.black]
line_length = 120

[tool.flake8]
count = true
ignore = ["E203,E402,E501,E731,E741,F841,RST2,RST30,RST401"]
per-file-ignores = ["__init__.py:F401"]
exclude = ["doc_assets/*","docs/*","notebook/*"]
max-line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
addopts = [
  "--color=yes",
  "--durations=0",
  "--strict-markers",
  "--doctest-modules",
]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
]
log_cli = "True"
log_cli_level = "DEBUG"
markers = [
  "slow: slow tests",
  "train: tests that train models",
]
minversion = "6.0"
testpaths = "tests/"

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
